import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const client = readFileSync(join(root, 'src/lib/ai/openrouter-video-client.ts'), 'utf8');
const service = readFileSync(join(root, 'src/lib/generations/openrouter-video-generation-service.ts'), 'utf8');
const route = readFileSync(join(root, 'src/app/api/v1/openrouter-video-generations/route.ts'), 'utf8');
const workspace = readFileSync(join(root, 'src/components/OpenRouterVideoProjectWorkspace.jsx'), 'utf8');
const page = readFileSync(join(root, 'src/app/projects/video/workspace/page.jsx'), 'utf8');
const migration = readFileSync(join(root, 'supabase/migrations/20260905204500_add_verified_seedance_20_mini_video_model.sql'), 'utf8');

assert.ok(client.includes("OPENROUTER_VIDEO_MODELS = ['bytedance/seedance-2.0-mini']"));
assert.ok(client.includes("OPENROUTER_VIDEO_RESOLUTIONS = ['480p', '720p']"));
assert.ok(client.includes("OPENROUTER_VIDEO_RATIOS = ['16:9', '9:16']"));
assert.ok(client.includes('OPENROUTER_VIDEO_MIN_DURATION = 4'));
assert.ok(client.includes('OPENROUTER_VIDEO_MAX_DURATION = 15'));
assert.ok(client.includes("const OPENROUTER_VIDEO_BASE = 'https://openrouter.ai/api/v1/videos'"));
assert.ok(client.includes('aspect_ratio: input.aspectRatio'));
assert.ok(client.includes('generate_audio: input.generateAudio'));
assert.ok(client.includes('process.env.OPENROUTER_API_KEY'));
assert.ok(client.includes("case 'pending': return 'queued'"));
assert.ok(client.includes("case 'in_progress': return 'processing'"));
assert.ok(client.includes("case 'completed': return 'succeeded'"));
assert.ok(client.includes("case 'expired': return 'failed'"));
assert.ok(client.includes('/content?index=0'));
assert.ok(client.includes("redirect: 'error'"));
assert.ok(client.includes('MAX_VIDEO_BYTES'));
assert.ok(!client.includes('unsigned_urls'), 'durable integration must download through the authenticated OpenRouter content endpoint');

assert.ok(service.includes("provider: 'openrouter'"));
assert.ok(service.includes('Math.max(minimumCredits, creditsPerSecond * duration)'));
assert.ok(service.includes('createOpenRouterVideoTask'));
assert.ok(service.includes('getOpenRouterVideoTask'));
assert.ok(service.includes('downloadOpenRouterVideo'));
assert.ok(service.includes("`video_refund_${generationIdValue}`"));
assert.ok(service.includes("'generation_failure_refund'"));
assert.ok(service.includes("const VIDEO_BUCKET = 'generation-video-assets'"));
assert.ok(service.includes("contentType: 'video/mp4'"));
assert.ok(service.includes('result_url: storagePath'));
assert.ok(service.includes(".eq('provider', 'openrouter')"));
assert.ok(service.includes("status: 'completed'"));
assert.ok(service.includes("status: 'failed'"));
assert.ok(service.includes("status: 'cancelled'"));

assert.ok(route.includes(".eq('provider', 'openrouter')"));
assert.ok(route.includes(".eq('generation_type', 'video')"));
assert.ok(route.includes(".eq('is_enabled', true)"));
assert.ok(route.includes(".eq('is_visible_to_users', true)"));
assert.ok(route.includes('validateOpenRouterVideoRequest'));
assert.ok(route.includes('OpenRouterVideoGenerationService.start'));
assert.ok(route.includes('OpenRouterVideoGenerationService.refresh'));
assert.ok(route.includes("return Boolean(process.env.OPENROUTER_API_KEY)"));
assert.ok(route.includes("provider: 'openrouter'"));
assert.ok(route.includes("error: 'VIDEO_MODEL_NOT_AVAILABLE'"));
assert.ok(route.includes("error: 'VIDEO_MODEL_PRICING_UNAVAILABLE'"));
assert.ok(route.includes("error: 'VIDEO_PROVIDER_NOT_CONFIGURED'"));
assert.ok(route.includes("projectTypeMatchesTool(project.type, 'video')"));

assert.ok(page.includes('OpenRouterVideoProjectWorkspace'));
assert.ok(workspace.includes("fetch('/api/v1/openrouter-video-generations'"));
assert.ok(workspace.includes('30000'), 'OpenRouter polling must use a bounded low-frequency UI interval');
assert.ok(workspace.includes('<video controls'));
assert.ok(workspace.includes("const RESOLUTIONS = ['480p', '720p']"));
assert.ok(workspace.includes('Math.max(Number(selectedModel.minimumCredits || 0), selectedModel.creditsPerSecond * duration)'));
assert.ok(workspace.includes('runtimeVerified'));
assert.ok(workspace.includes('insufficientCredits'));
assert.ok(workspace.includes('href="/pricing"'));
assert.ok(workspace.includes('bb-app-canvas'));
assert.ok(workspace.includes('bb-panel'));
assert.ok(workspace.includes('bb-input'));
assert.ok(workspace.includes('bb-button-primary'));
assert.ok(workspace.includes('bg-black object-contain'));

assert.ok(migration.includes("'bytedance/seedance-2.0-mini'"));
assert.ok(migration.includes("'openrouter'"));
assert.ok(migration.includes("'video'"));
assert.ok(migration.includes('0.01345'));
assert.ok(migration.includes("'brandbox_credits_per_second', 5"));
assert.ok(migration.includes("'runtime_verified', TRUE"));
assert.ok(migration.includes("'runtime_verified_at', '2026-09-05'"));
assert.ok(migration.includes("'supported_resolutions', jsonb_build_array('480p', '720p')"));
assert.ok(migration.includes("'supported_ratios', jsonb_build_array('16:9', '9:16')"));
assert.ok(migration.includes("'minimum_duration_seconds', 4"));
assert.ok(migration.includes("'maximum_duration_seconds', 15"));
assert.ok(migration.includes("ARRAY['video/mp4']"));
assert.ok(migration.includes('is_enabled = TRUE'));
assert.ok(migration.includes('is_visible_to_users = TRUE'));

console.log('OpenRouter permanent video integration guard passed.');
