import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const client = readFileSync(join(root, 'src/lib/ai/runway-client.ts'), 'utf8');
const service = readFileSync(join(root, 'src/lib/generations/video-generation-service.ts'), 'utf8');
const route = readFileSync(join(root, 'src/app/api/v1/video-generations/route.ts'), 'utf8');
const workspace = readFileSync(join(root, 'src/components/VideoProjectWorkspace.jsx'), 'utf8');
const page = readFileSync(join(root, 'src/app/projects/video/workspace/page.jsx'), 'utf8');
const adminRoute = readFileSync(join(root, 'src/app/api/v1/admin/ai-integrations/route.ts'), 'utf8');
const adminWorkspace = readFileSync(join(root, 'src/components/AdminAIIntegrationsPanel.jsx'), 'utf8');
const migration = readFileSync(join(root, 'supabase/migrations/20260902023000_runway_video_catalog_launch_seed.sql'), 'utf8');
const pricingMigration = readFileSync(join(root, 'supabase/migrations/20260902135442_price_runway_gen45_video.sql'), 'utf8');

assert.ok(client.includes("RUNWAY_VIDEO_MODELS = ['gen4.5']"));
assert.ok(client.includes("RUNWAY_TEXT_TO_VIDEO_RATIOS = ['1280:720', '720:1280']"));
assert.ok(client.includes('RUNWAY_TEXT_TO_VIDEO_MIN_DURATION = 2'));
assert.ok(client.includes('RUNWAY_TEXT_TO_VIDEO_MAX_DURATION = 10'));
assert.ok(client.includes('/v1/text_to_video'));
assert.ok(!client.includes('/v1/image_to_video'), 'text-only Gen-4.5 requests must use Runway text_to_video');
assert.ok(client.includes('/v1/tasks/'));
assert.ok(client.includes("'X-Runway-Version': RUNWAY_API_VERSION"));
assert.ok(client.includes('process.env.RUNWAYML_API_SECRET'));
assert.ok(!client.includes('error?.message'), 'provider internals must not be surfaced by the Runway client');
assert.ok(!client.includes('gen3a_turbo'));
assert.ok(!client.includes('runway-gen3-alpha'));

const post = route.slice(route.indexOf('export async function POST'), route.indexOf('export async function PATCH'));
const catalogIndex = post.indexOf(".from('ai_model_catalog')");
const serviceStartIndex = post.indexOf('VideoGenerationService.start');
assert.ok(catalogIndex >= 0 && serviceStartIndex > catalogIndex, 'video catalog checks must happen before credit reservation/service start');
assert.ok(post.includes(".eq('provider', 'runway')"));
assert.ok(post.includes(".eq('generation_type', 'video')"));
assert.ok(post.includes(".eq('is_enabled', true)"));
assert.ok(post.includes(".eq('is_visible_to_users', true)"));
assert.ok(post.includes("error: 'VIDEO_MODEL_NOT_AVAILABLE'"));
assert.ok(post.includes("error: 'VIDEO_MODEL_PRICING_UNAVAILABLE'"));
assert.ok(post.includes("error: 'VIDEO_PROVIDER_NOT_CONFIGURED'"));
assert.ok(post.includes('modelCreditsPerSecond(model.metadata)'));
assert.ok(post.includes('safeMinimumCredits(model.minimum_credits)'));
assert.ok(post.includes('{ creditsPerSecond, minimumCredits }'));
assert.ok(post.includes('ownedVideoProject'));
assert.ok(route.includes("projectTypeMatchesTool(project.type, 'video')"), 'ownedVideoProject must enforce video project type');
assert.ok(post.includes('validateRunwayVideoRequest'));
assert.ok(!route.includes('CreditEngine.calculateRequiredCredits'), 'video route must never fall back to generic hardcoded model pricing');

assert.ok(service.includes("status: 'queued'"));
assert.ok(service.includes("status: 'processing'"));
assert.ok(service.includes("status: 'completed'"));
assert.ok(service.includes("status: 'failed'"));
assert.ok(service.includes("'failed' | 'cancelled'"), 'provider cancellation must remain a typed terminal state');
assert.ok(service.includes("task.status === 'cancelled'"));
assert.ok(service.includes("`video_refund_${generationId}`"));
assert.ok(service.includes("'generation_failure_refund'"));
assert.ok(service.includes('Math.max(minimumCredits, creditsPerSecond * duration)'), 'minimum credits must be a real server-side floor');
assert.ok(service.includes("const VIDEO_BUCKET = 'generation-video-assets'"));
assert.ok(service.includes('downloadRunwayVideo(task.outputUrls[0])'));
assert.ok(service.includes("redirect: 'error'"), 'provider output downloads must not follow unvalidated redirects');
assert.ok(service.includes('result_url: storagePath'));
assert.ok(!service.includes('result_url: task.outputUrls'), 'ephemeral Runway URLs must never be stored as durable result URLs');
assert.ok(service.includes("contentType: 'video/mp4'"));
assert.ok(service.includes('MAX_VIDEO_BYTES'));
assert.ok(service.includes('isIP(hostname) !== 0'), 'provider output download must reject IP-literal SSRF targets');
assert.ok(service.includes(".eq('user_id', actor.userId)"));
assert.ok(service.includes(".eq('generation_type', 'video')"));
const providerRefreshCatch = service.slice(service.indexOf('catch (providerError)'), service.indexOf("if (task.status === 'queued'"));
assert.ok(providerRefreshCatch.includes('refundVideoCredits'), 'non-transient reconciliation errors must not leave credits reserved forever');
assert.ok(providerRefreshCatch.includes("status: 'failed'"));

assert.ok(page.includes('VideoProjectWorkspace'));
assert.ok(!page.includes('MediaProjectWorkspace'));
assert.ok(workspace.includes("fetch('/api/v1/video-generations'"));
assert.ok(workspace.includes("method: 'PATCH'"));
assert.ok(workspace.includes('6000 + Math.floor(Math.random() * 1200)'));
assert.ok(workspace.includes('<video controls'));
assert.ok(workspace.includes('إعادة المحاولة'));
assert.ok(workspace.includes('providerConfigured'));
assert.ok(workspace.includes('creditsPerSecond'));
assert.ok(!workspace.includes('Runway Gen-3 Alpha'));

assert.ok(adminRoute.includes('function hasRunwaySecret'));
assert.ok(adminRoute.includes('runwayConfigured: hasRunwaySecret()'));
assert.ok(adminRoute.includes("error: 'RUNWAY_SECRET_REQUIRED'"));
assert.ok(adminRoute.includes("error: 'VIDEO_PRICING_REQUIRED'"));
assert.ok(adminRoute.includes('brandboxCreditsPerSecond'));
assert.ok(adminRoute.includes('brandbox_credits_per_second'));
assert.ok(!adminRoute.includes("provider === 'openrouter' ? hasOpenRouterSecret() : true"), 'unknown providers must not be reported configured by default');
assert.ok(adminWorkspace.includes('Runway: {secretPolicy.runwayConfigured'));
assert.ok(adminWorkspace.includes('BB / sec'));
assert.ok(adminWorkspace.includes('Brand Box credits / second'));

assert.ok(migration.includes("'generation-video-assets'"));
assert.match(migration, /'generation-video-assets',[\s\S]*?FALSE,[\s\S]*?157286400/);
assert.ok(migration.includes("ARRAY['video/mp4']"));
assert.ok(migration.includes("'gen4.5'"));
assert.ok(migration.includes("'runway'"));
assert.ok(migration.includes("'video'"));
assert.ok(migration.includes("'brandbox_credits_per_second', 0"));
assert.ok(migration.includes("'provider_runway_credits_per_second', 12"));
assert.match(migration, /\n\s*0,\n\s*FALSE,\n\s*FALSE,/);
assert.ok(!migration.includes('is_enabled = EXCLUDED.is_enabled'));
assert.ok(!migration.includes('minimum_credits = EXCLUDED.minimum_credits'));

assert.ok(pricingMigration.includes('minimum_credits = 50'));
assert.ok(pricingMigration.includes("'brandbox_credits_per_second', 25"));
assert.ok(pricingMigration.includes("'provider_runway_credits_per_second', 12"));
assert.ok(pricingMigration.includes("'provider_usd_per_second', 0.12"));
assert.ok(pricingMigration.includes("'pricing_fx_lyd_per_usd', 13"));
assert.ok(pricingMigration.includes("'pricing_margin_floor_pct', 40"));
assert.ok(!pricingMigration.includes('is_enabled = TRUE'), 'pricing migration must not activate provider without its secret');
assert.ok(!pricingMigration.includes('is_visible_to_users = TRUE'), 'pricing migration must not expose provider without its secret');

console.log('Video generation launch guard passed.');
