BEGIN;

INSERT INTO public.ai_model_catalog (
  model_id,
  provider,
  generation_type,
  display_name_ar,
  display_name_en,
  pricing_mode,
  reservation_multiplier,
  minimum_credits,
  is_enabled,
  is_visible_to_users,
  sort_order,
  metadata,
  pricing_checked_at,
  vendor_name,
  tool_category,
  public_description_ar,
  public_description_en,
  minimum_plan_id,
  is_featured,
  updated_at
) VALUES
  (
    'openai/gpt-image-2',
    'openrouter',
    'image',
    'BRAND BOX Pro',
    'GPT Image 2',
    'image',
    1,
    6,
    TRUE,
    TRUE,
    10,
    jsonb_build_object('brandbox_badge', 'الأفضل', 'launch_catalog', 'image_v1'),
    NOW(),
    'OpenAI',
    'image',
    'نموذج صور احترافي للنتائج التجارية عالية الجودة.',
    'Professional image model for high-quality commercial results.',
    'starter',
    TRUE,
    NOW()
  ),
  (
    'bytedance-seed/seedream-5-0-lite',
    'openrouter',
    'image',
    'Seedream 5 Lite',
    'Seedream 5.0 Lite',
    'image',
    1,
    4,
    TRUE,
    TRUE,
    20,
    jsonb_build_object('brandbox_badge', 'سريع', 'launch_catalog', 'image_v1'),
    NOW(),
    'ByteDance Seed',
    'image',
    'نموذج سريع وعملي لإنشاء الصور والمفاهيم البصرية.',
    'Fast practical model for image generation and visual exploration.',
    'starter',
    FALSE,
    NOW()
  ),
  (
    'google/gemini-3.1-flash-lite-image',
    'openrouter',
    'image',
    'Nano Banana 2 Lite',
    'Gemini 3.1 Flash Lite Image',
    'image',
    1,
    4,
    TRUE,
    TRUE,
    30,
    jsonb_build_object('brandbox_badge', 'اقتصادي', 'launch_catalog', 'image_v1'),
    NOW(),
    'Google',
    'image',
    'نموذج صور سريع واقتصادي للاستخدام اليومي والاستكشاف.',
    'Fast cost-efficient image model for everyday generation and exploration.',
    'starter',
    FALSE,
    NOW()
  )
ON CONFLICT (model_id) DO UPDATE SET
  provider = EXCLUDED.provider,
  generation_type = EXCLUDED.generation_type,
  display_name_ar = EXCLUDED.display_name_ar,
  display_name_en = EXCLUDED.display_name_en,
  vendor_name = EXCLUDED.vendor_name,
  tool_category = EXCLUDED.tool_category,
  public_description_ar = EXCLUDED.public_description_ar,
  public_description_en = EXCLUDED.public_description_en,
  metadata = COALESCE(public.ai_model_catalog.metadata, '{}'::jsonb) || EXCLUDED.metadata,
  updated_at = NOW();

COMMIT;
